[project]
name = "shadoof"
version = "0.1.1"
description = "Command line utility for writing to hilltop from xmls and dsns of xmls"
authors = [
    {name = "SIrvine1994", email = "sam.irvine@horizons.govt.nz"}
]
license = "GNU General Public License v3"
requires-python = ">=3.14.1,<4.0"
dependencies = [
    "typer (>=0.27.1,<0.28.0)",
    "whurl (>=0.2.1,<0.3.0)",
    "pyodbc (>=5.3.0,<6.0.0)",
    "pywin32 (>=312,<313)"

]

[project.scripts]
shadoof = "shadoof.cli:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.bumpversion]
current_version = "0.1.1"
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = "src/shadoof/__init__.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "readme.rst"
search = "{current_version}"
replace = "{new_version}"